package fr.inria.kairos.lfranca;

public enum TraceEvent {
    REACTION_STARTS,
    REACTION_ENDS,
    SCHEDULE_CALLED,
    USER_EVENT,
    USER_VALUE,
    WORKER_WAIT_STARTS,
    WORKER_WAIT_ENDS,
    WORKER_ADVANCING_TIME_STARTS,
    WORKER_ADVANCING_TIME_ENDS
}
